language: ruby
rvm:
  - 2.4.1
services:
  - postgresql
env:
  - RAILS_ENV=test
install:
  - bundle install
  - nvm install stable && nvm alias default stable
  - npm install npm@latest -g
  - npm install -g yarn
  - npm --version
  - yarn install
before_script:
  - cp config/database.travis.yml config/database.yml
  - cp .env.travis .env
script:
  - bundle exec rake db:test:prepare
  - bundle exec rspec
