version: '3.3' # compatible with docker engine -v 17.06
# creates a private network between services
# each service is one docker image, but can be scaled horizontally to several container
services:
  db:
    image: postgres:9.6 # explicit version to prevent breakage with updates
    environment:
      - POSTGRES_PASSWORD # value will be read from local environment when run
    volumes:
      - dbdata:/var/lib/postgresql/data
    env_file:
      - ".env"
  redis:
    image: redis:3.2-alpine
    volumes:
    - redis:/data
  web:
    build: .
    environment:
      - RAILS_DB_HOSTNAME=db # db is both the service name and the host
      - REDIS_HOST=redis
      - RAILS_DB_PASS=${POSTGRES_PASSWORD}
      - RAILS_ADMIN_USER_PASS # value will be read from local env when run
    depends_on:
      - db
      - redis
    env_file:
      - ".env"
# ...and here
volumes:
  #data-volume: uncomment once the volumes used by the app are clear
  dbdata:
  redis:

## Deploy on server:

#> git clone/pull <repo>   <-- To get the last version of this file
#> export POSTGRES_PASSWORD="<secretpassword>"
#> export RAILS_ADMIN_USER_PASS="<secretadminpassword>"
#> docker-compose pull    <-- pulls images from the registry
#> docker-compose up -d --force-recreate  <-- less downtime to switch versions


## Maintenance:
# Open a bash on the web or db container
#> docker-compose exec web bash
#> docker-compose exec db bash
