version: '3.3'
services:
  web:
    image: mbellgb/hatch-site-prod # assumes image is on docker hub
    build:
      dockerfile: ./Dockerfile
    env_file: .env.prod.final
    environment:
      - RAILS_ENV=production
