version: '3.3'
services:
  web:
    image: mbellgb/hatch-site-prod # assumes image is on docker hub
    build:
      dockerfile: ./Dockerfile
    command: ["sh", "run-prod.sh"]
    environment:
      - RAILS_ENV=production
