redis: &redis
  adapter: redis
  url: <%= "redis://#{ENV.fetch('REDIS_HOST', 'localhost')}:6379/1" %>

development: *redis

test:
  adapter: async

production:
  <<: *redis
  channel_prefix: hatch-site_production
